### ISSUE TITLE
Build 1.1.0

### ISSUE THREAD

**Issue by doddsiedodds** [conda-forge/dbt-feedstock#65]
### Comment:

Hi - is it possible to update the recipe for the 1.1.0 release? I wasn't sure if there was a bot command to get this to happen automatically

**Comment by maresb** [comment]
Thanks for the ping @doddsiedodds, it is probably time to ping the staged recipes team.

Probably the holdup is that this will take an extra iteration in order to transfer the permissions. It's nothing particularly complicated, just that the important people are naturally very busy.

**Comment by doddsiedodds** [comment]
I pinged the admins on the staged recipes PR so that's now been merged and the feedstocks created eg: https://github.com/conda-forge/dbt-snowflake-feedstock

Just needs kicking for a build I think

**Comment by maresb** [comment]
Yes, it will take a few hours to trigger those builds and for everything to propagate to the CDN.

I think `dbt-core` is up-to-date, no? Is there anything else to take care of here?

**Comment by doddsiedodds** [comment]
dbt-core is indeed up-to-date, I'll wait for the snowflake build to propagate over the weekend in that case. Many thanks for your help!

**Comment by maresb** [comment]
Thanks for your persistence in seeing this through! We are still blocked by https://github.com/conda-forge/feedstock-outputs/pull/36, but hopefully this will be resolved soon.

**Comment by maresb** [comment]
I don't see any complaints so I'm going to close this as done. (Let me know if there's still some problem and we can reopen.)

**Comment by doddsiedodds** [comment]
Sorry, rude of me to not follow up - Thanks very much for fixing this, I've managed to pull the update. Thanks again

**Comment by maresb** [comment]
Awesome, no worries! :smile:
